spring:
  security :
    oauth2 :
      client :
        registration :
          github:
            clientId: 0b586df9ce10cac1a8c4
            clientSecret: 8788b17b1cd138243e58a8d04a9ec421c96b0e46
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

          google :
            client-id : 1011036415264-bs070fpmajp5q1jba6pgr9pes3nugsga.apps.googleusercontent.com
            client-secret : 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
            scope : profile, email

          naver :
            client-id : 0H728ryrx3j2qkJHWSZp
            client-secret : _yZfGPNNlI
            redirect-uri : '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type : authorization_code
            scope : email
            client-name: Naver

          kakao :
            client-id : e5d71dff711a6ce1502633381ca7f030
            client-secret : 45MSXUsqZXmLhpdKmxHXspBVmpNVqJtZ
            clientAuthenticationMethod : post
            authorization-grant-type : authorization_code
            redirect-uri : '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope : profile_nickname, account_email
            client-name: Kakao

        provider :
          naver :
            authorization-uri : https://nid.naver.com/oauth2.0/authorize
            token-uri : https://nid.naver.com/oauth2.0/token
            user-info-uri : https://openapi.naver.com/v1/nid/me
            user-name-attribute : response

          kakao :
            authorizationUri : https://kauth.kakao.com/oauth/authorize
            tokenUri : https://kauth.kakao.com/oauth/token
            userInfoUri : https://kapi.kakao.com/v2/user/me
            userNameAttribute : id

          github:
            authorization-uri : https://github.com/login/oauth/authorize
            token-uri : https://github.com/login/oauth/access_token
            user-info-uri : https://api.github.com/user
